### ISSUE TITLE
HangulUtils.py 에러

### ISSUE THREAD

**Issue by edwardyoon** [tdplaza/Tacotron-2-Korean#1]
아래와 같은 KeyError가 뜨는데요, 왜 그런것일까요?

Exception in thread background:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/Tacotron-2-Korean/Utils/Feeder.py", line 156, in _enqueue_next_train_group
    examples = [self._get_next_example() for i in range(n * _batches_per_group)]
  File "/home/ubuntu/Tacotron-2-Korean/Utils/Feeder.py", line 156, in <listcomp>
    examples = [self._get_next_example() for i in range(n * _batches_per_group)]
  File "/home/ubuntu/Tacotron-2-Korean/Utils/Feeder.py", line 183, in _get_next_example
    input_data = np.asarray(hangul_to_sequence(dir=hparams.base_dir, hangul_text=text, hangul_type=hparams.hangul_type), dtype=np.int32)
  File "/home/ubuntu/Tacotron-2-Korean/Utils/TextProcessing/HangulUtils.py", line 64, in hangul_to_sequence
    sequence = [hangul_to_ids[char] for char in hangul_text]
  File "/home/ubuntu/Tacotron-2-Korean/Utils/TextProcessing/HangulUtils.py", line 64, in <listcomp>
    sequence = [hangul_to_ids[char] for char in hangul_text]
KeyError: 'ᄌ'

Exception in thread background:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/Tacotron-2-Korean/Utils/Feeder.py", line 168, in _enqueue_next_test_group
    test_batches, r = self.make_test_batches()
  File "/home/ubuntu/Tacotron-2-Korean/Utils/Feeder.py", line 142, in make_test_batches
    examples = [self._get_test_groups() for i in range(len(self._test_meta))]
  File "/home/ubuntu/Tacotron-2-Korean/Utils/Feeder.py", line 142, in <listcomp>
    examples = [self._get_test_groups() for i in range(len(self._test_meta))]
  File "/home/ubuntu/Tacotron-2-Korean/Utils/Feeder.py", line 129, in _get_test_groups
    input_data = np.asarray(hangul_to_sequence(dir=hparams.base_dir, hangul_text= text, hangul_type=hparams.hangul_type), dtype=np.int32)
  File "/home/ubuntu/Tacotron-2-Korean/Utils/TextProcessing/HangulUtils.py", line 64, in hangul_to_sequence
    sequence = [hangul_to_ids[char] for char in hangul_text]
  File "/home/ubuntu/Tacotron-2-Korean/Utils/TextProcessing/HangulUtils.py", line 64, in <listcomp>
    sequence = [hangul_to_ids[char] for char in hangul_text]
KeyError: 'ᄆ'

**Comment by edwardyoon** [comment]
아, 확인되었네요.
